variables:
  GIT_DEPTH: 1

workflow:
  rules:
    - if: $ENVIRONMENT_SUFFIX
      when: always
    - when: never

stages:
  - build
  - deploy

build_and_push_staging:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u=gitlab-ci-user -p=$GITLAB_CI_TOKEN
    - docker build --network=host --tag reg.sighup.io/kage/one-b:$CI_COMMIT_SHORT_SHA .
    - docker push reg.sighup.io/kage/one-b:$CI_COMMIT_SHORT_SHA

deploy_staging:
  stage: deploy
  image: quay.io/sighup/kubectl-kustomize:1.18.2_3.6.1
  before_script:
    - cd kubernetes/staging
  script:
    - sed -i "s/@@ENVIRONMENT_SUFFIX@@/$ENVIRONMENT_SUFFIX/g" patch/ingress-host.yml
    - kustomize build > /dev/null
    - kustomize edit set image reg.sighup.io/kage/one-b:$CI_COMMIT_SHORT_SHA
    - kustomize edit set namespace $ENVIRONMENT_NAME
    - kustomize build | kubectl apply -f -
