apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kage-demo

patchesJson6902:
  - path: patch/ingress-host.yml
    target:
      group: extensions
      kind: Ingress
      name: one-b-backend-internal
      version: v1beta1

resources:
  - deploy.yml
  - ingress.yml
  - ns.yml
